name: AllNationsBible-Flutter 
on:
 push: 
     branches: [ "main" ] 
 pull_request: 
     branches: [ "main" ] 
  
jobs: 
 build-apk: 
   runs-on: windows-latest 
   steps: 
        - uses: actions/checkout@v3 
        - uses: actions/setup-java@v2 
          with: 
            distribution: 'zulu' 
            java-version: '11' 
            cache: gradle 
        - name: Flutter action 
          uses: subosito/flutter-action@v2.8.0 
          with: 
            flutter-version: '3.x' 
            channel: 'stable' 
            cache: true 
            cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' 
            cache-path: ${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:cache 
            architecture: x64 
        - run: flutter --version 
        - run: flutter config --no-analytics 
        - run: flutter pub get 
        - run: flutter build apk 
        - uses: actions/upload-artifact@v3 
          with: 
            name: main-apk 
            path: build\app\outputs\flutter-apk\
